import 'package:flutter/material.dart';
import '../models/business_models.dart';
import '../services/database_service.dart';
import 'app_shell.dart';

class ExpensesView extends StatelessWidget { final List<Expense> items; final VoidCallback onChanged; const ExpensesView({super.key,required this.items,required this.onChanged});
 @override Widget build(BuildContext context)=>Scaffold(body:ListView(padding:const EdgeInsets.all(12),children:[const Text('Expenses Log',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...items.map((x)=>Card(child:ListTile(title:Text(x.category),subtitle:Text('${x.date} • ${x.description} • ${x.paymentMethod}'),trailing:Text(money(x.amount)),onLongPress:()async{if(x.id!=null)await DatabaseService.instance.deleteExpense(x.id!);onChanged();})))]),floatingActionButton:FloatingActionButton(onPressed:()=>_add(context),child:const Icon(Icons.add)));
 Future<void> _add(BuildContext context)async{final cat=TextEditingController(),desc=TextEditingController(),amount=TextEditingController(),pay=TextEditingController(); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Expenses Log'),content:SingleChildScrollView(child:Column(children:[TextField(controller:cat,decoration:const InputDecoration(labelText:'Expense Category / Name')),TextField(controller:desc,decoration:const InputDecoration(labelText:'Description / Details')),TextField(controller:amount,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Amount (TZS)')),TextField(controller:pay,decoration:const InputDecoration(labelText:'Payment Method'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('SAVE'))]));if(ok==true){await DatabaseService.instance.addExpense(Expense(date:DateTime.now().toIso8601String().substring(0,10),category:cat.text,description:desc.text,amount:double.tryParse(amount.text)??0,paymentMethod:pay.text));onChanged();}}
}
