import 'package:flutter/material.dart';
import '../models/business_models.dart';
import '../services/database_service.dart';
import 'app_shell.dart';

class InventoryView extends StatelessWidget { final List<Inventory> items; final VoidCallback onChanged; const InventoryView({super.key,required this.items,required this.onChanged});
 @override Widget build(BuildContext context)=>Scaffold(body:ListView(padding:const EdgeInsets.all(12),children:[const Text('Inventory Log',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),...items.map((x)=>Card(child:ListTile(title:Text(x.product),subtitle:Text('${x.unitPack} • Opening: ${x.openingQty} • Closing: ${x.closingQty}'),trailing:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.end,children:[Text(money(x.openingValue)),Text(money(x.closingValue),style:const TextStyle(fontSize:11)),],),onLongPress:()async{if(x.id!=null)await DatabaseService.instance.deleteInventory(x.id!);onChanged();})))]),floatingActionButton:FloatingActionButton(onPressed:()=>_add(context),child:const Icon(Icons.add)));
 Future<void> _add(BuildContext context)async{final p=TextEditingController(),u=TextEditingController(),c=TextEditingController(),o=TextEditingController(),cl=TextEditingController();final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Inventory Log'),content:SingleChildScrollView(child:Column(children:[TextField(controller:p,decoration:const InputDecoration(labelText:'Product Name ')),TextField(controller:u,decoration:const InputDecoration(labelText:'Unit / Pack')),TextField(controller:c,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:' Per Unit Cost Price  - TZS)')),TextField(controller:o,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Opening Quantities')),TextField(controller:cl,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Closing quantities'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('SAVE'))]));if(ok==true){await DatabaseService.instance.addInventory(Inventory(product:p.text,unitPack:u.text,unitCost:double.tryParse(c.text)??0,openingQty:double.tryParse(o.text)??0,closingQty:double.tryParse(cl.text)??0));onChanged();}}
}
