import 'package:flutter/material.dart';
import '../models/business_models.dart';
import '../services/database_service.dart';
import 'app_shell.dart';

class SalesView extends StatelessWidget { final List<Sale> items; final VoidCallback onChanged; const SalesView({super.key,required this.items,required this.onChanged});
  @override Widget build(BuildContext context)=>Scaffold(body:ListView(padding:const EdgeInsets.all(12),children:[_header(context),...items.map((x)=>Card(child:ListTile(title:Text(x.item),subtitle:Text('${x.date} • ${x.quantity} × ${money(x.unitPrice)}'),trailing:Text(money(x.revenue)),onLongPress:()async{if(x.id!=null)await DatabaseService.instance.deleteSale(x.id!);onChanged();})))]),floatingActionButton:FloatingActionButton(onPressed:()=>_add(context),child:const Icon(Icons.add)));
  Widget _header(BuildContext c)=>const Padding(padding:EdgeInsets.only(bottom:10),child:Text('Sales Log',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)));
  Future<void> _add(BuildContext context)async{final item=TextEditingController(),price=TextEditingController(),qty=TextEditingController(),cost=TextEditingController(text:'0'); final ok=await showDialog<bool>(context:context,builder:(_)=>AlertDialog(title:const Text('Sales Log'),content:SingleChildScrollView(child:Column(children:[TextField(controller:item,decoration:const InputDecoration(labelText:'Item / Category')),TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Unit Price (TZS)')),TextField(controller:qty,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Quantity Sold')),TextField(controller:cost,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Product Unit Cost (TZS)'))])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(context,true),child:const Text('SAVE'))])); if(ok==true){await DatabaseService.instance.addSale(Sale(date:DateTime.now().toIso8601String().substring(0,10),item:item.text,unitPrice:double.tryParse(price.text)??0,quantity:double.tryParse(qty.text)??0,productUnitCost:double.tryParse(cost.text)??0));onChanged();}}
}
